version: '3.4'

services:

  web:
    build:
      context: .
      dockerfile: Dockerfile

    ports:
     - 8000:8000
    command: [
      'uvicorn', 'app:app',
      '--host', '0.0.0.0',
      '--port', '8000'
    ]
    depends_on:
      - redis

  worker:
    build: .
    command: [
      'celery', '-A', 'tasks:celery_app', 'worker' 
    ] 
    depends_on:
      - web
      - redis

  redis:
    container_name: redis
    image: redis:latest

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:latest
